In [1]:
import xarray as xr
import numpy as np
from matplotlib import pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
from cartopy.mpl.ticker import LongitudeFormatter, LatitudeFormatter

In [2]:
#lon_range = c(143, 207)
#lat_range = c(-16, 30)

lon_min = 143.
lon_max = 207.
lat_min = -16.
lat_max = 30.

In [3]:
url_dhw = 'https://oceanwatch.pifsc.noaa.gov/erddap/griddap/CRW_dhw_v1_0'
dhw_ds = xr.open_dataset(url_dhw)
dhw_ds

<xarray.Dataset>
Dimensions:              (time: 14327, latitude: 3600, longitude: 7200)
Coordinates:
  * time                 (time) datetime64[ns] 1985-03-25T12:00:00 ... 2024-0...
  * latitude             (latitude) float32 89.97 89.93 89.88 ... -89.93 -89.97
  * longitude            (longitude) float32 0.025 0.075 0.125 ... 359.9 360.0
Data variables:
    degree_heating_week  (time, latitude, longitude) float32 ...
Attributes: (12/64)
    acknowledgement:            NOAA Coral Reef Watch program
    cdm_data_type:              Grid
    comment:                    This is a product of the NOAA Coral Reef Watc...
    contributor_name:           NOAA Coral Reef Watch Program
    contributor_role:           Collecting source data and deriving products;...
    Conventions:                CF-1.6, ACDD-1.3, COARDS
    ...                         ...
    time_coverage_duration:     P1D
    time_coverage_end:          2024-06-16T12:00:00Z
    time_coverage_resolution:   P1D
    time_coverage_start:        1985-03-25T12:00:00Z
    title:                      Degree Heating Week, Coral Reef Watch - Daily...
    Westernmost_Easting:        0.025

In [4]:
dhw_subset = dhw_ds['degree_heating_week'].sel(
                                     latitude=slice(lat_max, lat_min),
                                     longitude=slice(lon_min, lon_max)
                                     )
dhw_subset

<xarray.DataArray 'degree_heating_week' (time: 14327, latitude: 920,
                                         longitude: 1280)>
[16871475200 values with dtype=float32]
Coordinates:
  * time       (time) datetime64[ns] 1985-03-25T12:00:00 ... 2024-06-16T12:00:00
  * latitude   (latitude) float32 29.98 29.92 29.88 ... -15.88 -15.93 -15.98
  * longitude  (longitude) float32 143.0 143.1 143.1 143.2 ... 206.9 206.9 207.0
Attributes:
    colorBarMaximum:        20.0
    colorBarMinimum:        0.0
    coverage_content_type:  physicalMeasurement
    grid_mapping:           crs
    ioos_category:          Temperature
    long_name:              degree heating week
    standard_name:          n/a
    units:                  degree_Celsius_weeks
    valid_max:              100.0
    valid_min:              0.0

In [23]:
mon_field=[]
for yr in range(1985,2025):
    
    st_yr = str(yr)+'-01-01'
    end_yr = str(yr)+'-12-31'
    dhw_temp = dhw_subset.sel(time=slice(st_yr,end_yr))
    #print(dhw_temp)
    mon_temp = dhw_temp.groupby('time.month').mean('time')
    print(mon_temp)
    mon_field.append(mon_temp)
mon_field

<xarray.DataArray 'degree_heating_week' (month: 10, latitude: 920,
                                         longitude: 1280)>
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ],
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ],
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.      

[<xarray.DataArray 'degree_heating_week' (month: 10, latitude: 920,
                                          longitude: 1280)>
 array([[[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         ...,
         [       nan,        nan,        nan, ..., 0.        ,
          0.        , 0.        ],
         [       nan,        nan,        nan, ..., 0.        ,
          0.        , 0.        ],
         [       nan,        nan,        nan, ..., 0.        ,
          0.        , 0.        ]],
 
        [[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
        

In [39]:
mon_field[0]

<xarray.DataArray 'degree_heating_week' (month: 10, latitude: 920,
                                         longitude: 1280)>
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ],
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ],
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ],
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ],
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.07225806, ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ],
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ],
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ]]], dtype=float32)
Coordinates:
  * latitude   (latitude) float32 29.98 29.92 29.88 ... -15.88 -15.93 -15.98
  * longitude  (longitude) float32 143.0 143.1 143.1 143.2 ... 206.9 206.9 207.0
  * month      (month) int64 3 4 5 6 7 8 9 10 11 12
Attributes:
    colorBarMaximum:        20.0
    colorBarMinimum:        0.0
    coverage_content_type:  physicalMeasurement
    grid_mapping:           crs
    ioos_category:          Temperature
    long_name:              degree heating week
    standard_name:          n/a
    units:                  degree_Celsius_weeks
    valid_max:              100.0
    valid_min:              0.0

In [43]:
#np.array(mon_field[1:-1]).shape
TS=[]

for j in range(0,10):
    TS.append(mon_field[0][j,:,:])
        
for i in range(1,39):
    for j in range(0,12):
        TS.append(mon_field[i][j,:,:])
    
for j in range(0,5):
    TS.append(mon_field[-1][j,:,:])

In [45]:
np.array(TS).shape

(471, 920, 1280)

In [48]:
fn='./ACCESS-CM2_r1i1p1f1_zg_1900_to_2100_regridded.nc'
ref = xr.open_dataset(fn)
ref.close()

In [50]:
dhw_mon= xr.DataArray(np.array(TS),                                 
          name='sst',             
          coords={'time':ref.time.sel(time=slice('1985-03-01','2024-05-31')),'latitude':dhw_subset.latitude,'longitude':dhw_subset.longitude },    
          dims=('time','latitude','longitude') )
dhw_mon

<xarray.DataArray 'sst' (time: 471, latitude: 920, longitude: 1280)>
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ],
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ],
        [       nan,        nan,        nan, ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [       nan,        nan,        nan, ..., 5.892335  ,
         5.8776655 , 6.000001  ],
        [       nan,        nan,        nan, ..., 5.7770004 ,
         6.0149994 , 5.9663324 ],
        [       nan,        nan,        nan, ..., 5.9523325 ,
         5.806     , 6.0513353 ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [       nan,        nan,        nan, ..., 5.3091316 ,
         5.291739  , 5.421738  ],
        [       nan,        nan,        nan, ..., 5.3104353 ,
         5.4382615 , 5.2704353 ],
        [       nan,        nan,        nan, ..., 5.4443483 ,
         5.1360865 , 5.2760878 ]]], dtype=float32)
Coordinates:
  * time       (time) datetime64[ns] 1985-03-16T12:00:00 ... 2024-05-16T12:00:00
  * latitude   (latitude) float32 29.98 29.92 29.88 ... -15.88 -15.93 -15.98
  * longitude  (longitude) float32 143.0 143.1 143.1 143.2 ... 206.9 206.9 207.0

In [51]:
dhw_mon.to_netcdf('./dhw_monthly.nc')